In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_excel("housepriceair_final.xlsx")

In [3]:
df

constant   CT o_station  month           hp    air           pop  inc  \
0           1  宜蘭縣   冬山(冬山區)      1  221751.6190  27.01    665.852742  590   
1           1  宜蘭縣   冬山(冬山區)      2  174516.1957  35.54    665.802655  590   
2           1  宜蘭縣   冬山(冬山區)      3  143657.7154  38.72    664.750814  590   
3           1  宜蘭縣   冬山(冬山區)      4  181408.3219  51.12    663.110443  590   
4           1  宜蘭縣   冬山(冬山區)      5  157317.5083  36.50    663.536188  590   
..        ...  ...       ...    ...          ...    ...           ...  ...   
847         1  臺南市   臺南(中西區)      8  190143.3828  25.41  12450.798720  655   
848         1  臺南市   臺南(中西區)      9  174250.0904  46.89  12458.785940  655   
849         1  臺南市   臺南(中西區)     10  169953.1429  67.50  12474.920130  655   
850         1  臺南市   臺南(中西區)     11  164338.8639  68.77  12480.191690  655   
851         1  臺南市   臺南(中西區)     12  171902.2292  72.22  12486.741210  655   

     d_tra1      h_age     h_area  PM2.5  SO2  d_north  d_middle  d_east  
0         1   9.967200  32.968091   11.6  2.3        1         0       0  
1         1  14.800000  61.073182   10.4  1.9        1         0       0  
2         1  18.526300  50.280697   21.9  2.4        1         0       0  
3         1  16.758600  46.637697   13.8  3.2        1         0       0  
4         1  13.666600  50.577636   11.8  2.4        1         0       0  
..      ...        ...        ...    ...  ...      ...       ...     ...  
847       1  23.827586  58.289812   34.8  2.8        0         0       0  
848       1  24.596154  50.410140    7.8  1.5        0         0       0  
849       1  24.698413  48.557143    6.9  1.2        0         0       0  
850       1  29.655738  53.865176    8.4  1.3        0         0       0  
851       1  27.107692  59.607972    3.7  1.5        0         0       0  

[852 rows x 16 columns]

In [4]:
# use package
from statsmodels.formula.api import ols

model = ols('hp ~ air + pop + inc + d_tra1 + h_age + h_area', data = df).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                     hp   R-squared:                       0.592
Model:                            OLS   Adj. R-squared:                  0.589
Method:                 Least Squares   F-statistic:                     194.7
Date:                Wed, 03 Feb 2021   Prob (F-statistic):          5.27e-153
Time:                        22:43:23   Log-Likelihood:                -10526.
No. Observations:                 812   AIC:                         2.107e+04
Df Residuals:                     805   BIC:                         2.110e+04
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -2.961e+05   4.72e+04     -6.278      0.000   -3.89e+05   -2.04e+05
air        -1709.2834    219.024     -7.804      0.000   -2139.210   -1279.357
pop            7.6267      0.509     14.992      0.000       6.628       8.625
inc          756.4747     66.750     11.333      0.000     625.449     887.500
d_tra1      3.698e+04   7905.940      4.677      0.000    2.15e+04    5.25e+04
h_age       2628.7847    530.377      4.956      0.000    1587.699    3669.870
h_area      -268.2911    204.775     -1.310      0.191    -670.247     133.665
==============================================================================
Omnibus:                      429.268   Durbin-Watson:                   0.388
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5265.311
Skew:                           2.108   Prob(JB):                         0.00
Kurtosis:                      14.741   Cond. No.                     1.44e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.44e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

# Hypothesis Testing
## t Test

In [5]:
# 去掉不需要的column
df_X = df.drop(labels = 'CT', axis = 1)
df_X = df_X.drop(labels = 'o_station', axis = 1)
df_X = df_X.drop(labels = 'month', axis = 1)
df_X = df_X.drop(labels = 'hp', axis = 1)
df_X = df_X.drop(labels = 'd_north', axis = 1)
df_X = df_X.drop(labels = 'd_middle', axis = 1)
df_X = df_X.drop(labels = 'd_east', axis = 1)
df_X = df_X.drop(labels = 'PM2.5', axis = 1)
df_X = df_X.drop(labels = 'SO2', axis = 1)
df_X

constant    air           pop  inc  d_tra1      h_age     h_area
0           1  27.01    665.852742  590       1   9.967200  32.968091
1           1  35.54    665.802655  590       1  14.800000  61.073182
2           1  38.72    664.750814  590       1  18.526300  50.280697
3           1  51.12    663.110443  590       1  16.758600  46.637697
4           1  36.50    663.536188  590       1  13.666600  50.577636
..        ...    ...           ...  ...     ...        ...        ...
847         1  25.41  12450.798720  655       1  23.827586  58.289812
848         1  46.89  12458.785940  655       1  24.596154  50.410140
849         1  67.50  12474.920130  655       1  24.698413  48.557143
850         1  68.77  12480.191690  655       1  29.655738  53.865176
851         1  72.22  12486.741210  655       1  27.107692  59.607972

[852 rows x 7 columns]

In [6]:
# 去掉nan值
df_X2 = df_X.dropna()
df_X2

constant    air           pop  inc  d_tra1      h_age     h_area
0           1  27.01    665.852742  590       1   9.967200  32.968091
1           1  35.54    665.802655  590       1  14.800000  61.073182
2           1  38.72    664.750814  590       1  18.526300  50.280697
3           1  51.12    663.110443  590       1  16.758600  46.637697
4           1  36.50    663.536188  590       1  13.666600  50.577636
..        ...    ...           ...  ...     ...        ...        ...
847         1  25.41  12450.798720  655       1  23.827586  58.289812
848         1  46.89  12458.785940  655       1  24.596154  50.410140
849         1  67.50  12474.920130  655       1  24.698413  48.557143
850         1  68.77  12480.191690  655       1  29.655738  53.865176
851         1  72.22  12486.741210  655       1  27.107692  59.607972

[812 rows x 7 columns]

In [7]:
# 把dataframe轉乘matrix
X_matr = df_X2.values

In [8]:
# 2d matrix
X_matr.shape

(812, 7)

In [9]:
df_y = df.dropna()

In [10]:
# 1d matrix
y = df_y['hp'].values

In [11]:
y_matr = y.reshape(812, 1)

In [12]:
# 2d matrix
y_matr.shape

(812, 1)

In [13]:
# 算出Beta hat
C = X_matr.transpose().dot(X_matr)
C_inv = np.linalg.inv(C)
B_hat = C_inv.dot(X_matr.transpose()).dot(y_matr)

In [14]:
y_hat = X_matr.dot(B_hat)

In [15]:
e_hat = y_matr - y_hat

In [16]:
sigmasquare_hat = e_hat.transpose().dot(e_hat) / (len(y) - len(B_hat))

In [17]:
# Var(y) = sigma_square 之估計式
sigmasquare_hat

array([[1.07273333e+10]])

In [18]:
import math 

In [19]:
sigmasquare_hat_2 = sigmasquare_hat[0][0]
sigma_hat = math.sqrt(sigmasquare_hat_2)
sigma_hat

103572.84054268137

### Ho: Bi = 0

In [20]:
for i in range(7):
    a = np.array([[0,0,0,0,0,0,0]])
    a[0][i] = 1
    R = np.array([[0,0,0,0,0,0,0]]) + a
    m = R.dot(C_inv).dot(R.transpose())  # R(X'X)^(-1)R'
    m_2 = m[0][0]
    t_statistic = B_hat[i][0] / (sigma_hat * math.sqrt(m_2))
    print('t-ratio',i,'=',t_statistic)

t-ratio 0 = -6.277805543863521
t-ratio 1 = -7.804081589746833
t-ratio 2 = 14.992037553547188
t-ratio 3 = 11.332873761733813
t-ratio 4 = 4.677375823106141
t-ratio 5 = 4.956443562436785
t-ratio 6 = -1.3101753071696909


### Ho: 3B2 + 2B3 = 0

In [21]:
R = np.array([[0, 0, 3, 2, 0, 0, 0]])
m = R.dot(C_inv).dot(R.transpose())
m_2 = m[0][0]
t_statistic = R.dot(B_hat)[0][0] / (sigma_hat * math.sqrt(m_2))
print('t_statistic =',t_statistic)

t_statistic = 11.574212557750071


### Ho: B1 + B2 = 1

In [22]:
R = np.array([[0, 1, 1, 0, 0, 0, 0]])
m = R.dot(C_inv).dot(R.transpose())
m_2 = m[0][0]
t_statistic = (R.dot(B_hat)[0][0] - 1) / (sigma_hat * math.sqrt(m_2))
print('t_statistic =',t_statistic)

t_statistic = -7.773729406579266


# R square

In [23]:
tss = y_matr.transpose().dot(y_matr)[0][0]
tss

63123055140805.97

In [24]:
# regression sum of square
rss = y_hat.transpose().dot(y_hat)[0][0]
rss

54487551835854.72

In [25]:
# error sum of square
ess = e_hat.transpose().dot(e_hat)[0][0]
ess

8635503304954.158

In [26]:
R2 = rss / tss
R2

0.8631957327526624

# Centered R square

In [27]:
y_bar = np.mean(y_matr)
y_bar

227305.9216427217

In [28]:
# y_bar = yhat_bar
yhat_bar = np.mean(y_hat)
yhat_bar

227305.92164272952

In [29]:
Ctss = 0
for i in range(len(y_matr)):
    Ctss = Ctss + (y_matr[i][0] - y_bar)**2
Ctss

21168653745562.11

In [30]:
Crss = 0
for i in range(len(y_hat)):
    Crss = Crss + (y_hat[i][0] - yhat_bar)**2
Crss

12533150440607.963

In [31]:
Cess = e_hat.transpose().dot(e_hat)[0][0]
Cess

8635503304954.158

In [32]:
CR2 = Crss / Ctss
CR2

0.592061762228761

# Adjusted R square

In [33]:
adjR2 = 1 - ( (len(y)-1)/(len(y)-len(B_hat)) ) * (1 - CR2)
adjR2

0.5890212287795343

In [34]:
print('R square =',R2)
print('Centered R square =',CR2)
print('Adjusted R square =',adjR2)

R square = 0.8631957327526624
Centered R square = 0.592061762228761
Adjusted R square = 0.5890212287795343


# Joint Hypothesis Testing
## F Test

### Ho: B1=0, B2=0, ..... , B6=0

In [35]:
R = np.zeros((6, 7))
for i in range(6):
    R[i][i+1] = 1
R

array([[0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [36]:
# (R*B_hat-r)'
a = R.dot(B_hat)
a_tr = a.transpose()

In [37]:
a

array([[-1.70928341e+03],
       [ 7.62667111e+00],
       [ 7.56474708e+02],
       [ 3.69790506e+04],
       [ 2.62878469e+03],
       [-2.68291126e+02]])

In [38]:
a_tr

array([[-1.70928341e+03,  7.62667111e+00,  7.56474708e+02,
         3.69790506e+04,  2.62878469e+03, -2.68291126e+02]])

In [39]:
# [R(X'X)^-1R']^-1
b = R.dot(C_inv).dot(R.transpose())
b = np.linalg.inv(b)
b

array([[ 2.37131666e+05, -1.47851855e+07, -7.15102514e+04,
        -8.29172857e+02, -1.54815782e+04,  4.78002088e+04],
       [-1.47851855e+07,  6.72391083e+10,  2.52636192e+08,
         1.05786041e+06,  1.26485796e+07, -3.08525080e+07],
       [-7.15102514e+04,  2.52636192e+08,  3.54108268e+06,
         4.62149754e+03, -3.39231286e+04, -3.59405496e+04],
       [-8.29172857e+02,  1.05786041e+06,  4.62149754e+03,
         1.94719212e+02,  5.29266168e+02, -1.43159188e+03],
       [-1.54815782e+04,  1.26485796e+07, -3.39231286e+04,
         5.29266168e+02,  4.48674739e+04, -2.33386457e+04],
       [ 4.78002088e+04, -3.08525080e+07, -3.59405496e+04,
        -1.43159188e+03, -2.33386457e+04,  2.87226364e+05]])

In [40]:
W_statistic = (a_tr.dot(b).dot(a)) / (6 * sigmasquare_hat)
print('W_statistic(F statistic) =',W_statistic[0][0])

W_statistic(F statistic) = 194.7229892765538


### H0:B1=2, B2+B3=1

In [41]:
R = np.array([[0,2,0,0,0,0,0], [0,0,1,1,0,0,0]])
R

array([[0, 2, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0]])

In [42]:
r = np.array([[2,1]])
r.shape

(1, 2)

In [43]:
r = r.reshape(2,1)
r.shape

(2, 1)

In [44]:
a = R.dot(B_hat) - r
a_tr = a.transpose()

In [45]:
b = R.dot(C_inv).dot(R.transpose())
b = np.linalg.inv(b)

In [46]:
W_statistic = (a_tr.dot(b).dot(a)) / (2 * sigmasquare_hat)
print('W_statistic =',W_statistic[0][0])

W_statistic = 102.02406028457706


# Use Centered R square to test Ho: B1=0, B2=0, ..... , B6=0

In [47]:
W = ( CR2 * (len(y)-len(B_hat)) ) / ( 6 * (1 - CR2) )
W

194.72298927655427